third commit 2

diff --git a/.github/workflows/third.yml b/.github/workflows/third.yml
--- a/.github/workflows/third.yml
+++ b/.github/workflows/third.yml
@@ -102,10 +102,10 @@ jobs:
       - name: Final Status
         run: echo "CI pipeline finished."
 
-      - name: Intentional Failure (Debug Demo)
-        run: |
-          echo "Simulating failure for debugging..."
-          exit 1
+    #   - name: Intentional Failure (Debug Demo)
+    #     run: |
+    #       echo "Simulating failure for debugging..."
+    #       exit 1
 
     #   - name: Failure Handler
     #     if: failure()
